### ISSUE TITLE
Way to set TTL

### ISSUE THREAD

**Issue by danielandross** [bramstroker/zf2-fullpage-cache#36]
In the doc I missed a way to set the ttl for cache entries?

**Comment by bramstroker** [comment]
You can set the TTL at the configuration of the cache storage configuration. This same TTL will be used for all the pages which are stored in the cache.

    'strokercache' => [
        'storage_adapter' => [
            'name' => 'filesystem',
            'options' => [
                'cache_dir' => __DIR__ . '/../../data/cache',
                'ttl' => 3600
            ],
        ]
    ]

StrokerCache doesn't support specifying a TTL per cache rule, because the interface of the StorageAdapter doesn't support it. see https://github.com/zendframework/zf2/pull/5386.

If you want to manage invalidating the items on a more regular base, you are better off to implement some active purging strategies. i.e. using the strokercache service or CLI controller to clear certain cache when particular events happen in your application.

I'll write a small chapture in the manual for setting the TTL.

**Comment by bramstroker** [comment]
I've added TTL to the documentation.
