### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by Perfect-Web** [bramstroker/zf2-fullpage-cache#46]
```
Usage of Zend\ServiceManager\ConfigInterface as a constructor argument for StrokerCache\IdGenerator\IdGeneratorPluginManager is now deprecated
```

**Comment by rudracomputech** [comment]
Hi, Any solution for this deprecated errors? I am also getting below errors after installing this module.

Deprecated: Usage of Zend\ServiceManager\ConfigInterface as a constructor argument for StrokerCache\IdGenerator\IdGeneratorPluginManager is now deprecated in \ZendSkeletonApplication\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php on line 74

Deprecated: Zend\ServiceManager\AbstractPluginManager::__construct now expects a Interop\Container\ContainerInterface instance representing the parent container; please update your code in \ZendSkeletonApplication\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php on line 85

Deprecated: Usage of Zend\ServiceManager\AbstractPluginManager::setServiceLocator is deprecated since v3.0.0; please pass the container to the constructor instead in \ZendSkeletonApplication\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php on line 187

**Comment by bramstroker** [comment]
If you want a really quick fix you can set the error_reporting to get rid of deprecation warnings:

`error_reporting(E_ALL ^ E_DEPRECATED)`

I have started working on dropping support for zend servicemanager V2, that should get rid of all the deprecation warnings.
Could you guys please test this version in your application?

`composer require stroker/cache:v2.x-dev`

**Comment by drakulitka** [comment]
`composer require stroker/cache:v2.x-dev`
This version works without warnings of obsolescence!

When you want to start implementing
"Store directly to HTML files for max performance" ?

**Comment by bramstroker** [comment]
@drakulitka Thanks for testing. I will merge this branch and create a stable release.

Regarding serving HTML files:
See https://github.com/bramstroker/zf2-fullpage-cache/issues/33. There you can find some pointers how to get this to work. Here we are using apache rewrite rules. When you are using Nginx you have to figure out the configuration yourself.
It should work, but atm I am not using it myself and didn't have time to document it yet.
